# FROM: https://github.com/sebgl/htpc-download-box/blob/master/docker-compose.yml

version: "3"
services:
  vpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    hostname: gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${NORD_SERVICE_USER}
      - OPENVPN_PASSWORD=${NORD_SERVICE_PASS}
      - SERVER_COUNTRIES=Netherlands
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/24
    ports:
      # - 9117:9117  # Jackett
      # - 9696:9696  # Prowlarr
      # - 7878:7878  # Radarr
      # - 8686:8686  # Lidarr
      # - 8787:8787  # Readerr
      # - 8989:8989  # Sonarr
      # - 8191:8191  # FlareSolverr
      # qBitTorrent
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /${BASE_PATH}/Downloads/Torrents/torrent-blackhole:/downloads # place where to put .torrent files
      - /${BASE_PATH}/docker/media-server/.config/jackett:/config

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/prowlarr:/config

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    ports:
      - 8191:8191
    security_opt:
      - no-new-privileges:true
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/qbittorrent:/config
      - /${BASE_PATH}/Downloads/Torrents:/downloads

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /${BASE_PATH}/docker/media-server/.config/sonarr:/config
      - /${BASE_PATH}/docker/media-server/scripts:/scripts
      - /${BASE_PATH}/TV:/tv
      - /${BASE_PATH}/Downloads/Torrents:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /${BASE_PATH}/docker/media-server/.config/radarr:/config
      - /${BASE_PATH}/docker/media-server/scripts:/scripts
      - /${BASE_PATH}/Movies:/movies
      - /${BASE_PATH}/Downloads/Torrents:/downloads

  readarr:
    container_name: readarr
    image: linuxserver/readarr:develop
    restart: unless-stopped
    ports:
      - 8787:8787
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/readarr:/config
      - /${BASE_PATH}/Books:/books
      - /${BASE_PATH}/Downloads/Books:/downloads
      
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /${BASE_PATH}/docker/media-server/.config/lidarr:/config
      - /${BASE_PATH}/Downloads/Music:/music
      - /${BASE_PATH}/Downloads/Torrents:/downloads

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/bazarr:/config
      - /${BASE_PATH}/Movies:/movies
      - /${BASE_PATH}/TV:/tv
      
  emby:
    image: linuxserver/emby:latest
    container_name: emby
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /${BASE_PATH}/TV:/data/tvshows
      - /${BASE_PATH}/Movies:/data/movies
      - /${BASE_PATH}/docker/media-server/.config/emby:/config
    ports:
      - 8097:8096/tcp
      - 8096:8096/tcp
