# FROM: https://github.com/sebgl/htpc-download-box/blob/master/docker-compose.yml

version: "3"
services:
  vpn:
    image: "bubuntux/nordvpn:openvpn"
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      - TZ=${TZ}
      - USER=${NORD_USER}
      - PASS=${NORD_PASS}
      - COUNTRY=${NORD_COUNTRY}
      - NETWORK=${NORD_NETWORK}
      - PROTOCOL=UDP
    networks:
      - default
    ports:
      - 9117:9117
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    volumes:
      - /dev/net:/dev/net:z
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
      - ./.config/vpn:/vpn
    # command: 'server;user;password[;port]'

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    depends_on:
      - vpn
    network_mode: service:vpn
    # network_mode: host
    environment:
      - PUID=${PUID} # default user id, for downloaded files access rights
      - PGID=${PGID} # default group id, for downloaded files access rights
      - TZ=${TIMEZONE} # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /${BASE_PATH}/Downloads/Torrents/torrent-blackhole:/downloads # place where to put .torrent files
      - /${BASE_PATH}/docker/media-server/.config/jackett:/config # config files


  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/qbittorrent:/config
      - /${BASE_PATH}/Downloads/Torrents:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - jackett
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, for downloaded files access rights
      - PGID=${PGID} # default group id, for downloaded files access rights
      - TZ=${TIMEZONE} # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /${BASE_PATH}/docker/media-server/.config/sonarr:/config # config files
      - /${BASE_PATH}/TV:/tv # tv shows folder
      - /${BASE_PATH}/Downloads/Torrents:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - jackett
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, for downloaded files access rights
      - PGID=${PGID} # default group id, for downloaded files access rights
      - TZ=${TIMEZONE} # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /${BASE_PATH}/docker/media-server/.config/radarr:/config # config files
      - /${BASE_PATH}/Movies:/movies # movies folder
      - /${BASE_PATH}/Downloads/Torrents:/downloads # download folder

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
      - jackett
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, for downloaded files access rights
      - PGID=${PGID} # default group id, for downloaded files access rights
      - TZ=${TIMEZONE}
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/bazarr:/config
      - /${BASE_PATH}/Movies:/movies
      - /${BASE_PATH}/TV:/tv
