# FROM: https://github.com/sebgl/htpc-download-box/blob/master/docker-compose.yml

version: '3'
services:
  vpn:
    image: bubuntux/nordvpn
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - net_admin
    environment:
      - TZ=REDACTED
      - USER=REDACTED
      - PASS=REDACTED
      - COUNTRY=REDACTED
      - NETWORK=REDACTED
    networks:
      - default
    ports:
      - 9117:9117
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    volumes:
      - /dev/net:/dev/net:z
    # Put .ovpn configuration file in the /vpn directory (in "volumes:" above or
    # launch using the command line arguments, IE pick one:
      - ./.config/vpn:/vpn
    # command: 'server;user;password[;port]'

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    depends_on:
      - vpn
    network_mode: service:vpn
    # network_mode: host
    environment:
      - PUID=1024 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=Europe/London # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/Downloads/Torrents/torrent-blackhole:/downloads # place where to put .torrent files
      - /volume1/docker/media-server/.config/jackett:/config # config files

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: host # run on the vpn network
    environment:
      - PUID=1024 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=Europe/London # timezone
    volumes:
      - /volume1/Downloads/Torrents:/downloads # download folder
      - /volume1/docker/media-server/.config/deluge:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      - deluge
      - jackett
    network_mode: host
    environment:
      - PUID=1024 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=Europe/London # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/media-server/.config/sonarr:/config # config files
      - /volume1/TV:/tv # tv shows folder
      - /volume1/Downloads/Torrents:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    depends_on:
      - deluge
      - jackett
    network_mode: host
    environment:
      - PUID=1024 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=Europe/London # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/media-server/.config/radarr:/config # config files
      - /volume1/Movies:/movies # movies folder
      - /volume1/Downloads/Torrents:/downloads # download folder

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
      - jackett
    network_mode: host
    environment:
      - PUID=1024 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=Europe/London
    volumes:
      - /volume1/docker/media-server/.config/bazarr:/config
      - /volume1/Movies:/movies
      - /volume1/TV:/tv
