# FROM: https://github.com/sebgl/htpc-download-box/blob/master/docker-compose.yml

version: "3"
services:
  vpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${NORD_SERVICE_USER}
      - OPENVPN_PASSWORD=${NORD_SERVICE_PASS}
      - SERVER_COUNTRIES=Netherlands
    ports:
      - 9117:9117  # Jackett
      - 9696:9696  # Prowlarr
      # qBitTorrent
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /${BASE_PATH}/Downloads/Torrents/torrent-blackhole:/downloads # place where to put .torrent files
      - /${BASE_PATH}/docker/media-server/.config/jackett:/config

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/prowlarr:/config

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/qbittorrent:/config
      - /${BASE_PATH}/Downloads/Torrents:/downloads

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - jackett
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /${BASE_PATH}/docker/media-server/.config/sonarr:/config
      - /${BASE_PATH}/docker/media-server/scripts:/scripts
      - /${BASE_PATH}/TV:/tv
      - /${BASE_PATH}/Downloads/Torrents:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - jackett
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /${BASE_PATH}/docker/media-server/.config/radarr:/config
      - /${BASE_PATH}/docker/media-server/scripts:/scripts
      - /${BASE_PATH}/Movies:/movies
      - /${BASE_PATH}/Downloads/Torrents:/downloads

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  readarr:
    container_name: readarr
    image: linuxserver/readarr:develop
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/readarr:/config
      - /${BASE_PATH}/Books:/books
      - /${BASE_PATH}/Downloads/Books:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
      
  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
      - jackett
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /${BASE_PATH}/docker/media-server/.config/lidarr:/config
      - /${BASE_PATH}/Downloads/Music:/music
      - /${BASE_PATH}/Downloads/Torrents:/downloads

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
      - jackett
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/bazarr:/config
      - /${BASE_PATH}/Movies:/movies
      - /${BASE_PATH}/TV:/tv
      
  emby:
    image: linuxserver/emby:latest
    container_name: emby
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /${BASE_PATH}/TV:/data/tvshows
      - /${BASE_PATH}/Movies:/data/movies
      - /${BASE_PATH}/docker/media-server/.config/emby:/config
    ports:
      - 8097:8096/tcp
      - 8096:8096/tcp
    devices:
      - /dev/dri:/dev/dri
  
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /${BASE_PATH}/docker/media-server/.config/homer/assets:/www/assets
    ports:
      - 8000:8080
    environment:
      - UID=${PUID}
      - GID=${PGID}
    restart: unless-stopped
