# FROM: https://github.com/sebgl/htpc-download-box/blob/master/docker-compose.yml

version: '3'
services:
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1024 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=Europe/London # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/Downloads/Torrents/torrent-blackhole:/downloads # place where to put .torrent files
      - /volume1/docker/media-server/.config/jackett:/config # config files

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: host # run on the vpn network
    environment:
      - PUID=1024 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=Europe/London # timezone
    volumes:
      - /volume1/Downloads/Torrents/ongoing:/downloads # download folder
      - /volume1/docker/media-server/.config/deluge:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1024 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=Europe/London # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/media-server/.config/sonarr:/config # config files
      - /volume1/TV:/tv # tv shows folder
      - /volume1/Downloads/Torrents/ongoing:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1024 # default user id, for downloaded files access rights
      - PGID=100 # default group id, for downloaded files access rights
      - TZ=Europe/London # timezone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/media-server/.config/radarr:/config # config files
      - /volume1/Movies:/movies # movies folder
      - /volume1/Downloads/Torrents/ongoing:/downloads # download folder

  # vpn:
  #   container_name: vpn
  #   image: dperson/openvpn-client:latest
  #   cap_add:
  #     - net_admin # required to modify network interfaces
  #   restart: unless-stopped
  #   volumes:
  #     - /dev/net/tun:/dev/net/tun # tun device
  #     - ${HOME}/.vpn:/vpn # OpenVPN configuration
  #   ports:
  #     - 8112:8112 # port for deluge web UI to be reachable from local network
  #   command: '-r 192.168.1.0/24' # route local network traffic

  # nzbget:
  #   container_name: nzbget
  #   image: linuxserver/nzbget:latest
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - PUID=1024 # default user id, for downloaded files access rights
  #     - PGID=100 # default group id, for downloaded files access rights
  #     - TZ=Europe/London # timezone
  #   volumes:
  #     - /volume1/Downloads/ongoing:/downloads # download folder
  #     - /volume1/docker/media-server/.config/nzbget:/config # config files

  # plex-server:
  #   container_name: plex-server
  #   image: plexinc/pms-docker:latest
  #   restart: unless-stopped
  #   environment:
  #     - TZ=Europe/London # timezone
  #   network_mode: host
  #   volumes:
  #     - ${HOME}/.plex/db:/config # plex database
  #     - ${HOME}/.plex/transcode:/transcode # temp transcoded files
  #     - /media/${USER}/data1/downloads:/data # media library
